services:
  mariadb:
    image: mariadb:11.7-rc
    container_name: mariadb
    environment:
      MARIADB_ROOT_PASSWORD: password
      MARIADB_DATABASE: demo
    volumes:
      - ./schema.sql:/docker-entrypoint-initdb.d/schema.sql
      - ./walmart-products.csv:/walmart-products.csv
      - ./mariadb-data:/var/lib/mysql
    ports:
      - "3306:3306"
